name: Qleverfiles check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  format-check:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Checkout the repository for the qlever script
        uses: actions/checkout@v3
        with:
          path: qlever-control

      - name: Install the script locally
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 --version
          pip3 --version
          pip3 show setuptools wheel
          pip3 install -e .

      - name: Check that all the files in `src/qlever/Qleverfiles` parse.
        working-directory: ${{github.workspace}}/qlever-control
        run: |
          for QLEVERFILE in src/qlever/Qleverfiles/Qleverfile.*; do
            NAME=${QLEVERFILE##*.}
            printf "Checking Qleverfile for $NAME ... "
            rm -f Qleverfile
            qlever setup-config $NAME
            qlever get-data --show 2>/dev/null 2>&1
            qlever index --show 2>/dev/null 2>&1
            qlever start --show 2>/dev/null 2>&1
            qlever ui --show 2>/dev/null 2>&1
            echo "OK"
          done
